namespace FDAOpenAPI.WebUI.Models.Drug.ProductLabeling
{
    public class DrugProductLabelingResult
    {
        public List<string> Abuse { get; set; }
        public List<string> Abuse_table { get; set; }
        public List<string> Accessories { get; set; }
        public List<string> Accessories_Table { get; set; }
        public List<string> Active_Ingredient { get; set; }
        public List<string> Active_Ingredient_Table { get; set; }
        public List<string> Adverse_Reactions { get; set; }
        public List<string> Adverse_Reactions_Table { get; set; }
        public List<string> Alarms { get; set; }
        public List<string> Alarms_Table { get; set; }
        public List<string> Animal_Pharmacology_And_Or_Toxicology { get; set; }
        public List<string> Animal_Pharmacology_And_Or_Toxicology_Table { get; set; }
        public List<string> Ask_Doctor { get; set; }
        public List<string> Ask_Doctor_Table { get; set; }
        public List<string> Ask_Doctor_Or_Pharmacist { get; set; }
        public List<string> Ask_Doctor_Or_Pharmacist_Table { get; set; }
        public List<string> Assembly_Or_Installation_Instructions { get; set; }
        public List<string> Assembly_Or_Installation_Instructions_Table { get; set; }
        public List<string> Boxed_Warning { get; set; }
        public List<string> Boxed_Warning_Table { get; set; }
        public List<string> Calibration_Instructions { get; set; }
        public List<string> Calibration_Instructions_Table { get; set; }
        public List<string> Carcinogenesis_And_Mutagenesis_And_Impairment_Of_Fertility { get; set; }
        public List<string> Carcinogenesis_And_Mutagenesis_And_Impairment_Of_Fertility_Table { get; set; }
        public List<string> Cleaning { get; set; }
        public List<string> Cleaning_Table { get; set; }
        public List<string> Clinical_Pharmacology { get; set; }
        public List<string> Clinical_pharmacology_table { get; set; }
        public List<string> Clinical_studies { get; set; }
        public List<string> Clinical_studies_table { get; set; }
        public List<string> Compatible_accessories { get; set; }
        public List<string> Compatible_accessories_table { get; set; }
        public List<string> Components { get; set; }
        public List<string> Components_table { get; set; }
        public List<string> Contraindications { get; set; }
        public List<string> Contraindications_table { get; set; }
        public List<string> Controlled_substance { get; set; }
        public List<string> Controlled_substance_table { get; set; }
        public List<string> Dependence { get; set; }
        public List<string> Dependence_table { get; set; }
        public List<string> Description { get; set; }
        public List<string> Description_table { get; set; }
        public List<string> Diagram_of_device { get; set; }
        public List<string> Diagram_of_device_table { get; set; }
        public List<string> Disposal_and_waste_handling { get; set; }
        public List<string> Disposal_and_waste_handling_table { get; set; }
        public List<string> Do_not_use { get; set; }
        public List<string> Do_not_use_table { get; set; }
        public List<string> Dosage_and_administration { get; set; }
        public List<string> Dosage_and_administration_table { get; set; }
        public List<string> Dosage_forms_and_strengths { get; set; }
        public List<string> Dosage_forms_and_strengths_table { get; set; }
        public List<string> Drug_abuse_and_dependence { get; set; }
        public List<string> Drug_abuse_and_dependence_table { get; set; }
        public List<string> Drug_and_or_laboratory_test_interactions { get; set; }
        public List<string> Drug_and_or_laboratory_test_interactions_table { get; set; }
        public List<string> Drug_interactions { get; set; }
        public List<string> Drug_interactions_table { get; set; }
        public string Effective_time { get; set; }
        public List<string> Environmental_warning { get; set; }
        public List<string> Environmental_warning_table { get; set; }
        public List<string> Food_safety_warning { get; set; }
        public List<string> Food_safety_warning_table { get; set; }
        public List<string> General_precautions { get; set; }
        public List<string> General_precautions_table { get; set; }
        public List<string> Geriatric_use { get; set; }
        public List<string> Geriatric_use_table { get; set; }
        public List<string> Guaranteed_analysis_of_feed { get; set; }
        public List<string> Guaranteed_analysis_of_feed_table { get; set; }
        public List<string> Health_care_provider_letter { get; set; }
        public List<string> Health_care_provider_letter_table { get; set; }
        public List<string> Health_claim { get; set; }
        public List<string> Health_claim_table { get; set; }
        public List<string> How_supplied { get; set; }
        public List<string> How_supplied_table { get; set; }
        public string Id { get; set; }
        public List<string> Inactive_ingredient { get; set; }
        public List<string> Inactive_ingredient_table { get; set; }
        public List<string> Indications_and_usage { get; set; }
        public List<string> Indications_and_usage_table { get; set; }
        public List<string> Information_for_owners_or_caregivers { get; set; }
        public List<string> Information_for_owners_or_caregivers_table { get; set; }
        public List<string> Information_for_patients { get; set; }
        public List<string> Information_for_patients_table { get; set; }
        public List<string> Instructions_for_use { get; set; }
        public List<string> Instructions_for_use_table { get; set; }
        public List<string> Intended_use_of_the_device { get; set; }
        public List<string> Intended_use_of_the_device_table { get; set; }
        public List<string> Keep_out_of_reach_of_children { get; set; }
        public List<string> Keep_out_of_reach_of_children_table { get; set; }
        public List<string> Labor_and_delivery { get; set; }
        public List<string> Labor_and_delivery_table { get; set; }
        public List<string> Laboratory_tests { get; set; }
        public List<string> Laboratory_tests_table { get; set; }
        public List<string> Mechanism_of_action { get; set; }
        public List<string> Mechanism_of_action_table { get; set; }
        public List<string> Microbiology { get; set; }
        public List<string> Microbiology_table { get; set; }
        public List<string> Nonclinical_toxicology { get; set; }
        public List<string> Nonclinical_toxicology_table { get; set; }
        public List<string> Nonteratogenic_effects { get; set; }
        public List<string> Nonteratogenic_effects_table { get; set; }
        public List<string> Nursing_mothers { get; set; }
        public List<string> Nursing_mothers_table { get; set; }
        public OpenFda OpenFDA { get; set; }
        public List<string> Other_safety_information { get; set; }
        public List<string> Other_safety_information_table { get; set; }
        public List<string> Overdosage { get; set; }
        public List<string> Overdosage_table { get; set; }
        public List<string> Package_label_principal_display_panel { get; set; }
        public List<string> Package_label_principal_display_panel_table { get; set; }
        public List<string> Patient_medication_information { get; set; }
        public List<string> Patient_medication_information_table { get; set; }
        public List<string> Pediatric_use { get; set; }
        public List<string> Pediatric_use_table { get; set; }
        public List<string> Pharmacodynamics { get; set; }
        public List<string> Pharmacodynamics_table { get; set; }
        public List<string> Pharmacogenomics { get; set; }
        public List<string> Pharmacogenomics_table { get; set; }
        public List<string> Pharmacokinetics { get; set; }
        public List<string> Pharmacokinetics_table { get; set; }
        public List<string> Precautions { get; set; }
        public List<string> Precautions_table { get; set; }
        public List<string> Pregnancy { get; set; }
        public List<string> Pregnancy_table { get; set; }
        public List<string> Pregnancy_or_breast_feeding { get; set; }
        public List<string> Pregnancy_or_breast_feeding_table { get; set; }
        public List<string> Purpose { get; set; }
        public List<string> Purpose_table { get; set; }
        public List<string> Questions { get; set; }
        public List<string> Questions_table { get; set; }
        public List<string> Recent_major_changes { get; set; }
        public List<string> Recent_major_changes_table { get; set; }
        public List<string> References { get; set; }
        public List<string> References_table { get; set; }
        public List<string> Residue_warning { get; set; }
        public List<string> Residue_warning_table { get; set; }
        public List<string> Risks { get; set; }
        public List<string> Risks_table { get; set; }
        public List<string> Route { get; set; }
        public List<string> Route_table { get; set; }
        public List<string> Safe_handling_warning { get; set; }
        public List<string> Safe_handling_warning_table { get; set; }
        public List<string> Set_id { get; set; }
        public List<string> Spl_indexing_data_elements { get; set; }
        public List<string> Spl_indexing_data_elements_table { get; set; }
        public List<string> Spl_medguide { get; set; }
        public List<string> Spl_medguide_table { get; set; }
        public List<string> Spl_patient_package_insert { get; set; }
        public List<string> Spl_patient_package_insert_table { get; set; }
        public List<string> Spl_product_data_elements { get; set; }
        public List<string> Spl_product_data_elements_table { get; set; }
        public List<string> Spl_unclassified_section { get; set; }
        public List<string> Spl_unclassified_section_table { get; set; }
        public List<string> Statement_of_identity { get; set; }
        public List<string> Statement_of_identity_table { get; set; }
        public List<string> Stop_use { get; set; }
        public List<string> Stop_use_table { get; set; }
        public List<string> Storage_and_handling { get; set; }
        public List<string> Storage_and_handling_table { get; set; }
        public List<string> Summary_of_safety_and_effectiveness { get; set; }
        public List<string> Summary_of_safety_and_effectiveness_table { get; set; }
        public List<string> Teratogenic_effects { get; set; }
        public List<string> Teratogenic_effects_table { get; set; }
        public List<string> Troubleshooting { get; set; }
        public List<string> Troubleshooting_table { get; set; }
        public List<string> Use_in_specific_populations { get; set; }
        public List<string> Use_in_specific_populations_table { get; set; }
        public List<string> User_safety_warnings { get; set; }
        public List<string> User_safety_warnings_table { get; set; }
        public string Version { get; set; }
        public List<string> Warnings { get; set; }
        public List<string> Warnings_table { get; set; }
        public List<string> Warnings_and_cautions { get; set; }
        public List<string> Warnings_and_cautions_table { get; set; }
        public List<string> When_using { get; set; }
        public List<string> When_using_table { get; set; }
    }
}
